apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: order-service
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
